name: trady_mobile
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0
  shared_preferences: ^2.3.0
  image_picker: ^1.1.2
  http_parser: ^4.0.2
  google_fonts: ^6.2.1
  intl: ^0.20.2
  jwt_decode: ^0.3.1
  socket_io_client: ^3.1.2
  url_launcher: ^6.3.1
  font_awesome_flutter: ^10.7.0
  flutter_animate: ^4.0.0
  camera: ^0.11.0
  path_provider: ^2.1.1
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
